const ACTION_PREFIX = 'PLAYER';

export const INIT_ACTION = `${ACTION_PREFIX}_INIT_ACTION`;
export const SET_CURRENT_TIME_ACTION = `${ACTION_PREFIX}_SET_CURRENT_TIME`;
export const SET_MOUSE_ACTIVE_ACTION = `${ACTION_PREFIX}_SET_MOUSE_ACTIVE`;

export const ON_PLAY_ACTION = `${ACTION_PREFIX}_ON_PLAY`;
export const ON_PAUSE_ACTION = `${ACTION_PREFIX}_ON_PAUSE`;
export const ON_LOADED_META_DATA_ACTION = `${ACTION_PREFIX}_ON_LOADED_META_DATA`;
export const ON_WAITING_ACTION = `${ACTION_PREFIX}_ON_WAITING`;
export const ON_PLAYING_ACTION = `${ACTION_PREFIX}_ON_PLAYING`;
export const ON_DURATION_CHANGE_ACTION = `${ACTION_PREFIX}_ON_DURATION_CHANGE`;
export const ON_PROGRESS_ACTION = `${ACTION_PREFIX}_ON_PROGRESS`;
export const ON_TIME_UPDATE_ACTION = `${ACTION_PREFIX}_ON_TIME_UPDATE`;
export const ON_FULL_SCREEN_CHANGE_ACTION = `${ACTION_PREFIX}_ON_FULL_SCREEN_CHANGE`;
